##
## Copyright (c) 2015, 2016, 2017, 2018, 2019 The University of Utah
## Copyright (c) 2015 Tamir Duberstein
## All rights reserved.
##
## This file is distributed under the University of Illinois Open Source
## License.  See the file COPYING for details.
##

###############################################################################

sudo: required
dist: bionic
language: cpp

stages:
  - build

# podman is currently not in Ubuntu
addons:
  apt:
    update: true
    sources:
      - sourceline: "ppa:projectatomic/ppa"
    packages:
      - podman slirp4netns

matrix:
  - include:
    - name: DEBUG build (LLVM 9)
      stage: build
      env:
        - BUILD_TYPE=DEBUG
        - DIST=opensusetw-llvm9

    - name: DEBUG build (LLVM 10)
      stage: build
      env:
        - BUILD_TYPE=DEBUG
        - DIST=opensusetw-llvm10

    - name: UBSAN build (LLVM 10)
      stage: build
      env:
        - BUILD_TYPE=UBSAN
        - DIST=opensusetw-llvm10

    - name: ASAN build (LLVM 10)
      stage: build
      env:
        - BUILD_TYPE=ASAN
        - DIST=opensusetw-llvm10

    - name: Fedora 31 DEBUG build (LLVM 9)
      stage: build
      env:
        - BUILD_TYPE=DEBUG
        - DIST=fedora31-llvm9

before_install:
  # podman needs a basic register set up (packaging bug in the ppa)
  - sudo mkdir -p /etc/containers
  - echo -e "[registries.search]\nregistries = ['docker.io']" | sudo tee /etc/containers/registries.conf
  # we need to register travis to allow subuid/gid for the rootless execution
  - echo "travis:110000:65535" | sudo tee /etc/subuid
  - echo "travis:110000:65535" | sudo tee /etc/subgid

script:
  - podman build -t $DIST -f Docker/Dockerfile-$DIST .
  - podman run -v $(pwd):/usr/src/cvise $DIST ./build_and_test.sh

###############################################################################

## End of file.
