codecov:
  disable_default_path_fixes: no

fixes:
  - "/usr/src/cvise/objdir/usr/src/cvise/objdir::"
  - "/usr/src/cvise/objdir/usr/src/cvise::"
ignore:
  - "**/include"
  - "cvise/tests"
  - "/usr/src/cvise/objdir/delta/topformflat.c"
  - "/usr/src/cvise/objdir/clex/strlex.c"
  - "/usr/src/cvise/objdir/clex/clex.c"
