fixes:
  - "/usr/src/cvise/objdir/usr/src/cvise/objdir::"
  - "/usr/src/cvise/objdir/usr/src/cvise::"
ignore:
  - "**/include"
  - "cvise/tests"
  - "delta/topformflat.c"
  - "clex/strlex.c"
  - "clex/clex.c"
